import { thumbnailGaleriaModal } from "./thumbails";

export const imagensGaleriaModal = () => {
  return [
    {
      id: 1,
      nome_unico: "fachada",
      src: "images/principal/galeria/fachada.jpg",
      texto: "Perspectiva ilustrada da",
      textoDestaque: "Fachada",
    },
    {
      id: 2,
      nome_unico: "portaria",
      src: "images/principal/galeria/portaria.jpg",
      texto: "Perspectiva ilustrada da",
      textoDestaque: "Portaria",
    },
    {
      id: 3,
      nome_unico: "piscina",
      src: "images/principal/galeria/piscina-adulto.png",
      texto: "Perspectiva ilustrada da",
      textoDestaque: "Piscina Adulto",
    },
    {
      id: 4,
      nome_unico: "praca-central",
      src: "images/principal/galeria/praca-central.jpg",
      texto: "Perspectiva ilustrada da",
      textoDestaque: "Praça central",
    },
    {
      id: 5,
      nome_unico: "fitness-musculacao",
      src: "images/principal/galeria/fitness-musculacao.png",
      texto: "Perspectiva ilustrada ",
      textoDestaque: "Fitness Aeróbico",
    },
    {
      id: 6,
      nome_unico: "fitness-musculacao-2",
      src: "images/principal/galeria/fitness-musculacao-2.png",
      texto: "Perspectiva ilustrada ",
      textoDestaque: "Fitness musculação",
    },
    {
      id: 7,
      nome_unico: "salao-gourmet",
      src: "images/principal/galeria/salao-festas-gourmet.png",
      texto: "Perspectiva ilustrada do",
      textoDestaque: "Salão de festas gourmet",
    },
    {
      id: 8,
      nome_unico: "salao-festas",
      src: "images/principal/galeria/salao-de-festas.png",
      texto: "Perspectiva ilustrada do",
      textoDestaque: "Salão de festas",
    },
    {
      id: 9,
      nome_unico: "espaco-grill",
      src: "images/principal/galeria/espaco-grill.png",
      texto: "Perspectiva ilustrada do",
      textoDestaque: "Espaço grill",
    },
    {
      id: 10,
      nome_unico: "playground",
      src: "images/principal/galeria/playground.png",
      texto: "Perspectiva ilustrada do",
      textoDestaque: "Playground",
    },
    {
      id: 11,
      nome_unico: "brinquedoteca",
      src: "images/principal/galeria/brinquedoteca.png",
      texto: "Perspectiva ilustrada da",
      textoDestaque: "Brinquedoteca",
    },
    {
      id: 12,
      nome_unico: "salao-jogos-convivio",
      src: "images/principal/galeria/salao-jogos-convivio.png",
      texto: "Perspectiva ilustrada do",
      textoDestaque: "Salão de jogos - convivio",
    },
    {
      id: 13,
      nome_unico: "salao-jogos-convivio-2",
      src: "images/principal/galeria/salao-de-jogos-convivio-2.png",
      texto: "Perspectiva ilustrada do",
      textoDestaque: "Salão de jogos - convivio",
    },
    {
      id: 14,
      nome_unico: "lavanderia",
      src: "images/principal/galeria/lavanderia.png",
      texto: "Perspectiva ilustrada da",
      textoDestaque: "Lavanderia",
    },
    {
      id: 15,
      nome_unico: "hall",
      src: "images/principal/galeria/hall.png",
      texto: "Perspectiva ilustrada do",
      textoDestaque: "Hall",
    },
    {
      id: 16,
      nome_unico: "decorado-2",
      src: "images/principal/galeria/decorado/foto_decorado_7.jpg",
      texto: "Foto do",
      textoDestaque: "Decorado",
    },
    {
      id: 17,
      nome_unico: "decorado-3",
      src: "images/principal/galeria/decorado/foto_decorado_12.jpg",
      texto: "Foto do",
      textoDestaque: "Decorado",
    },
    {
      id: 18,
      nome_unico: "decorado-4",
      src: "images/principal/galeria/decorado/foto_decorado_15.jpg",
      texto: "Foto do",
      textoDestaque: "Decorado",
    },
    {
      id: 19,
      nome_unico: "decorado-5",
      src: "images/principal/galeria/decorado/foto_decorado_18.jpg",
      texto: "Foto do",
      textoDestaque: "Decorado",
    },

  ];
}
