const list = [
  "Facilities",
  "Facilities e Benefícios",
  "Auditoria",
  "Assistência Técnica",
  "Assistente de Diretoria",
  "Benefícios",
  "Comercial",
  "Conselho de Administração",
  "Contabilidade",
  "Contas a Pagar",
  "Contas a Pagar e Tesouraria",
  "Contas a Receber",
  "Crédito Imobiliário, Repasse e Registro",
  "Controladoria",
  "Crédito Imobiliário",
  "Central de Lançamentos",
  "Diretor de Relações com Investidores e Institucionais",
  "Diretor de Incorporação e Novos Negócios",
  "Diretor Presidente",
  "Diretor Financeiro",
  "Diretor de RI",
  "Diretora de Operações",
  "Desenvolvimento de Produto",
  "Departamento Pessoal",
  "Diretoria",
  "Escrituras",
  "Fiscal",
  "Incorporação",
  "Incorporação Ambiental",
  "Incorporação e Produto",
  "Infraestrutura",
  "Inteligência de Mercado",
  "Install",
  "Institucionais",
  "Juridico Contencioso",
  "Jurídico Imobiliário",
  "Marketing",
  "Marketing Digital",
  "Novos Negócios",
  "Obras RJ",
  "Obras SP",
  "Orçamentos",
  "Presidente",
  "Pagadoria",
  "Planejamento",
  "Planejamento Financeiro",
  "Planejamento e Orçamentos",
  "Processamento de Vendas",
  "Projeto Executivo",
  "Qualidade",
  "Recursos Humanos",
  "Registro",
  "Relacionamento Com Cliente",
  "Relações com Investidores",
  "Repasse",
  "Reversão",
  "SESMT",
  "Suprimentos",
  "Secretária Diretoria",
  "Secretária Presidência",
  "Tecnologia da Informação",
  "Tesouraria",
  "Vendas",
  "Vendas Digitais",
  "Vice-presidente comercial",
  "VP de Engenharia",
];

export function get_list() {
  const order = list.sort((a, b) => a[0].localeCompare(b[0]));

  return order;
}
